system:
  forceipv4: true
  domain: 'local'
  hostname: iombian
  country: ES
  timezone: 'Europe/Madrid'
  lang: 'es_ES.UTF-8'

user:
  name: iompi
  password: iompi
  #email: your@email.com

networking:
  eth0:
    profile: 'static'
    ip: '192.168.0.10/24'
    #gw: '192.168.0.1'
    #dns: 
      #- '8.8.8.8'
      #- '8.8.4.4'
  #eth1:
    #profile: 'dhcp'
  wlan0:
    profile: 'dhcp'
    wlan:
      ssid: ''
      psk: ''
    #wlan2:
      #ssid: ''
      #psk: ''

sshd: 
  enabled: false

avahi:
  ifaces: wlan0
  publish: true
  browsedomains: []
  publishdns:
    - 8.8.8.8

config_date: ''